POST http://localhost:3000/api/review/notify
Content-Type: application/json
{
	"name": "Тест 3",
	"title": "Заголовок",
	"description": "Описание тестовое",
	"rating": 5,
	"productId": "6041f7a3b3e24b1e15e98d38"
}



###

POST http://localhost:3000/api/review/create
Content-Type: application/json
{
	"name": "Тест 3",
	"title": "Заголовок",
	"description": "Описание тестовое",
	"rating": 5,
	"productId": "6041f7a3b3e24b1e15e98d38"
}'



###

GET http://localhost:3000/api/review/byProduct/603f519c245f4018275b73f1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEucnUiLCJpYXQiOjE2MTQ3ODM5Njh9.qME9vjdg4P_2xDJOAHDXPAdXKNtfncNSjlEy6g-nuTA

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json
{
  "login": "a@a.com",
  "password": "1"
}


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json
{
  "login": "a@a.com",
  "password": "1"
}


HTTP/1.1 200 - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 147
etag: W/"93-8Zhzxj3HhuwBLn1a3ZBjTjILL5Y"
date: Mon, 30 Aug 2021 15:18:56 GMT
connection: close

{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzAzMzY3MzZ9.u63SRaADFesYyvscaxBwqLDpxs4uPkSgrs9JJLjXgIk"}

/*
## GetProduct
``` bash
curl --request GET \
  --url http://localhost:3000/api/product/6040de091a2ac332d80ca788
```

## DeleteProduct
``` bash
curl --request DELETE \
  --url http://localhost:3000/api/product/6041f77bb3e24b1e15e98d37
```

## FindProduct
``` bash
curl --request POST \
  --url http://localhost:3000/api/product/find \
  --header 'Content-Type: application/json' \
  --data '{
	"category": "",
	"limit": 10
}'
```

## CreateProduct
``` bash
curl --request POST \
  --url http://localhost:3000/api/product/create \
  --header 'Content-Type: application/json' \
  --data '{
	"image": "1.png",
	"title": "Мой продукт",
	"price": 100,
	"oldPrice": 120,
	"credit": 10,
	"description": "Описание продукта",
	"advantages": "Преимущества продукта",
	"disAdvantages": "Недостатки продукта",
	"categories": ["тест"],
	"tags": ["тег1"],
	"characteristics": [{
		"name": "Характеристика 1",
		"value": "1"
	},{
		"name": "Характеристика 2",
		"value": "2"
	}]
}'
```

## UpdateProduct
``` bash
curl --request PATCH \
  --url http://localhost:3000/api/product/6041f77bb3e24b1e15e98d374 \
  --header 'Content-Type: application/json' \
  --data '{
	"image": "2.png",
	"title": "Мой продукт",
	"price": 100,
	"oldPrice": 120,
	"credit": 10,
	"description": "Описание продукта",
	"advantages": "Преимущества продукта",
	"disAdvantages": "Недостатки продукта",
	"categories": ["тест"],
	"tags": ["тег1"],
	"characteristics": [{
		"name": "Характеристика 1",
		"value": "1"
	},{
		"name": "Характеристика 2",
		"value": "2"
	}]
}'
```

*/
